# Generated by Django 3.2.19 on 2023-06-28 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('margin_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('buying_price', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('transportation', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('packaging', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('warehouse', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('marketplace_commission_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('recommended_price', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ProductInformation',
            },
        ),
        migrations.CreateModel(
            name='ProductInformationAdditionalFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_fields', to='calculator.productinformation')),
            ],
            options={
                'verbose_name_plural': 'ProductInformationAdditionalFields',
            },
        ),
    ]
